Dev
StephenKodua/onSale_App pull request #1
Opened 2022-06-22 22:36 UTC by StephenKodua

DAY 1 (login, sign up with parse)

2022-06-23 00:57 UTC, 3dm1 commented
I really like where this PR is going but want to push you to improve and make your code more concise. A comment about the commits/PR:
1. When you create the PR, please assign it a descriptive name. In this case "App authentication screens" would be enough
2. Remember that commits should be descriptive as well. Multiple commits called Launch Activity do not tell me about their contents - a better approach is to describe what's contained, i.e. "Add signup screen", "Handle error during authentication", etc.
3. This is on me because I forgot to tell you, but please add me as a reviewer when you create a PR
![Screen Shot 2022-06-22 at 5 57 20 PM](https://user-images.githubusercontent.com/7488039/175184997-d6e15826-b9d8-4d0f-b317-64e77733da6b.png)

2022-06-23 00:59 UTC, 3dm1 requested changes
I really like where this PR is going but want to push you to improve and make your code more concise. A comment about the commits/PR:
1. When you create the PR, please assign it a descriptive name. In this case "App authentication screens" would be enough
2. Remember that commits should be descriptive as well. Multiple commits called Launch Activity do not tell me about their contents - a better approach is to describe what's contained, i.e. "Add signup screen", "Handle error during authentication", etc.
3. This is on me because I forgot to tell you, but please add me as a reviewer when you create a PR
![Screen Shot 2022-06-22 at 5 57 20 PM](https://user-images.githubusercontent.com/7488039/175184997-d6e15826-b9d8-4d0f-b317-64e77733da6b.png)

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/AndroidManifest.xml
> +            android:name="com.example.onsalestore.LaunchActivity"
There are two possible ways to improve your approach to login:
1. Keep LaunchActivity as is, but refactor code to merge Login and SignupActivities into a single one. You can pass a parameter to this new activity via intent which will determine how the screen will look like and which string to use.
2. Refactor all these activities into a single one that uses fragments. The benefit is grouping features that are very similar close together.

Either way is fine, so feel free to pick one.

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +    Button btnLogin, btnSign;
It is a good practice to make these fields private.
```suggestion
    private Button btnLogin, btnSign;
```

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +                goLoginActivity();
Small nit, but naming should be very clear and contain all needed words.
```suggestion
                goToLoginActivity();
```

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +                goSignActivity();
```suggestion
                goToSignInActivity();
```

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LoginActivity.java
> +        }
I'd say that you should move this check to the `LaunchActivity` - if the user is already logged in, then they should be taken to the main screen directly without having to select sign up or login.

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LoginActivity.java
> +                    // for example notify user or send user to login again
A good way to track these todos is to create an issue here on GitHub so you don't forget about it.

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/LoginActivity.java
> +        startActivity(i);
You don't have to do it though, it's more a matter of preference. For such small cases, I'd also consider fine to inline the variable. 
```suggestion
        startActivity(new Intent (this, MainActivity.class));
```

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/SignupActivity.java
> +                    // Take appropriate action
You can set messages directly on `EditText` by using its `setError` method.

2022-06-23 00:59 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/SignupActivity.java
> +                            goLoginActivity();
I understand that you're doing this because it's the `LoginActivity` that eventually starts the `MainActivity`, but it's a flow that would cause some head scratching. The solution depends on how you plan to refactor the login/sign up pair of screens but ultimately what you need to do is to have the sign in/up screen send a signal back to the `LaunchActivity` telling it they were successful.

You can either rely on:
1. Activity results
2. A listener from the fragment to the parent activity

2022-06-23 16:40 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +    Button btnLogin, btnSign;
Done

2022-06-23 16:40 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +                goLoginActivity();
Done

2022-06-23 16:40 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/LaunchActivity.java
> +                goSignActivity();
Done

2022-06-23 16:40 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/LoginActivity.java
> +        }
Done

2022-06-24 16:21 UTC, 3dm1 requested changes
Hey Stephen, there's a big point I made about refactoring Login and Signup activities which you missed.

2022-06-24 16:21 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/SignupActivity.java
> +                            goLoginActivity();
This was not addressed.

2022-06-27 18:17 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/SignupActivity.java
> +                            goLoginActivity();
What I'm suggesting is to make `LaunchActivity` the component that will define how the authentication flow will happen. It would contain 3 fragments: The LaunchFragment, which contains the login/sign up buttons, the LoginFragment and the SignUpFragment (which you already have). It's up to the activity to switch between these fragments depending on how the user interacts with the screen and the back button. As an example:
1) User taps Sign In button and that fragment is shown
2) User presses back and is taken back to the screen with the login/sign up buttons again

The question then is how to make sure you go to the MainActivity when authentication is successful which is why I mentioned the listener. You can create a [custom listener](https://stackoverflow.com/questions/6941321/how-to-create-custom-listeners-in-java) that is passed to the fragment (through a setter method) when you're about to show it in screen, which the fragment can call once the authentication flow succeeds. The fragment calling the interface lets the LaunchActivity know that it can now move to the MainActivity.

2022-06-27 18:22 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +        tvBuyandsell = findViewById(R.id.tvBuyandSell);
Using snake case helps with readability - first letter is lower case and then all other words start with a capital letter.

```suggestion
        tvBuyAndSell = findViewById(R.id.tvBuyandSell);
```

2022-06-27 18:23 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +                return false;
Can you explain what this is doing? Seems like you're toggling an image every time someone touches it?

2022-06-27 18:23 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +        LinearLayoutManager CategoriesLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
```suggestion
        LinearLayoutManager categoriesLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
```

2022-06-27 18:24 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +                        goToLoginFragment();
Given you're navigating to a different screen, you should probably update this method name.

2022-06-27 18:26 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/Stores.java
> +public class Stores extends ParseObject {
Same comment as in Categories - I'd keep this name as a singular object.

2022-06-27 18:34 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +                return false;
Yeah. I was making the code more fun by changing pictures when it is touched. I can remove it, if you suggest.

2022-06-27 20:11 UTC, StephenKodua commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +                        goToLoginFragment();
Okay sure. Please what do you think of **returnToAuthentication()** ?

2022-06-27 20:24 UTC, 3dm1 commented
Sounds good to me.

On Mon, Jun 27, 2022, 1:11 PM Stephen Kodua ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/src/main/java/com/example/onsalestore/MainActivity.java
> <https://github.com/StephenKodua/onSale_App/pull/1#discussion_r907758273>:
>
> > +
> +    @Override
> +    public boolean onCreateOptionsMenu(Menu menu) {
> +        // Inflate the menu; this adds items to the action bar if it is present.
> +        getMenuInflater().inflate(R.menu.menu_main, menu);
> +        return true;
> +    }
> +
> +    @Override
> +    public boolean ***@***.*** MenuItem item) {
> +        //execute if menu item is tapped
> +        if (item.getItemId() == R.id.signOutItem) {
> +            ParseUser.logOutInBackground(new LogOutCallback() {
> +                public void done(ParseException e) {
> +                    if (e == null) {
> +                        goToLoginFragment();
>
> Okay sure. Please what do you think of *returnToAuthentication()* ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/StephenKodua/onSale_App/pull/1#discussion_r907758273>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZEEJ6G42DDHVKZOZ3V253VRIDITANCNFSM5ZSBZY5Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-06-28 15:23 UTC, 3dm1 approved these changes

2022-06-28 15:24 UTC, merged

2022-06-28 20:44 UTC, 3dm1 commented on app/src/main/java/com/example/onsalestore/MainActivity.java
> +                return false;
You're using `onTouchListener` which is a bit heavy handed, touch here means any interaction with the screen. If you look at the events it uses you have `TOUCH_UP`, `TOUCH_DOWN`, etc. - a tap, for instance, is a touch down followed by a touch up. So usually it's better to set use a click listener or using a timer to switch these images automatically.